// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO USERS (ID,CREATED_AT,UPDATED_AT,NAME,api_key)
VALUES ($1,$2,$3,$4,encode(sha256(random()::text::bytea), 'hex'))
RETURNING id, created_at, updated_at, name, api_key
`

type CreateUserParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ApiKey,
	)
	return i, err
}

const getUserByAPIKey = `-- name: GetUserByAPIKey :one



SELECT id, created_at, updated_at, name, api_key FROM USERS
WHERE API_KEY = $1 LIMIT 1
`

// we can still pass $5 but then we will have to use the sha256 function when we call this function
// instaed we directly did it here
// we need to change this file as we have added new column apikey
// before
// INSERT INTO USERS (ID,CREATED_AT,UPDATED_AT,NAME)
// VALUES ($1,$2,$3,$4)
// RETURNING *;
func (q *Queries) GetUserByAPIKey(ctx context.Context, apiKey string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByAPIKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ApiKey,
	)
	return i, err
}
