-- +goose up

CREATE TABLE FEEDS(
    ID UUID PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    NAME TEXT NOT NULL,
    URL TEXT UNIQUE NOT NULL,
    USER_ID UUID NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE
    
);
--DELETE CASCADE IS FOR IF A USER IS DELETED THEN ALL THE CORROSPONDING FEED WILL ALSO BE DELETED WITH IT

-- here we will store the list of different feeds that the user want 
-- +goose down 
DROP TABLE FEEDS;


