-- +goose up
CREATE TABLE FEED_FOLLOWER(
    ID UUID PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    USER_ID UUID NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    FEED_ID UUID NOT NULL REFERENCES FEEDS(ID) ON DELETE CASCADE,
    UNIQUE(USER_ID,FEED_ID)
);
-- +goose down
DROP TABLE IF EXISTS FEED_FOLLOWER;

--WE ENUSERRE HERE THAT THE COMBINED USER_ID AND FEED_ID 
--IS UNIQUE AS USER DONT FOLLOW SAME FEED TWICE OR MULTIPLE TIMES