-- +goose up
CREATE TABLE POSTS(
    ID UUID PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    TITLE TEXT NOT NULL,
    URL TEXT NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    PUBLISHED_AT TIMESTAMP NOT NULL,
    FEED_ID UUID NOT NULL REFERENCES FEEDS(ID) ON DELETE CASCADE
);
-- +goose down 
DROP TABLE POSTS;